## MySQL Connection properties
#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/employee_db
#    username: root
#    password: root
#
## Hibernate Properties
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#      show_sql: true
#      hbm2ddl.auto: update
#
## Server Port
#server:
#  port: 8080
#
## Swagger
#
#swagger:
#  api:
#    basePackage: com.example
#    title: Employee API
#    description: Employee API
#    version: 1.0
#    contact:
#      name: Jitendra
#      email:
